### ISSUE TITLE
Requirements.txt missing

### ISSUE THREAD

**Issue by ghost** [Pythonista7/Implementing_#1]
Use virtualenv and make sure a requirements file exists so that when people do clone, they're able to set the repo up.

**Comment by Pythonista7** [comment]
Hey thank you for your interest.
I would suggest that [colab](https://colab.research.google.com) for most of the python projects on this repo.
As dependencies are sometimes a hassle to install and some implementations such as the style transfer are computationally expensive and require hardware acceleration.I will make sure to add sufficiently more setup documentation henceforth for a local env set-up. Cheers :)
